### ISSUE TITLE
When `viewOrForm.$el` is undefined, use `$.find`, not `$.children`?

### ISSUE THREAD

**Issue by david-davidson** [marionettejs/backbone.syphon#104]
Hi there,

I just ran into trouble with form serialization in a Marionette app. Turns out my problem involved Syphon's `getForm` function--specifically, the fact that it uses `$.children`, not `$.find`, to look for form inputs when passed a specific form, not a view.

My use case: I was passing a form to Syphon using `Syphon.serialize(this.$('#my-form-id')[0])`. (My view was a CompositeView whose `$el` included other forms [introduced by child views], so `.serialize(this)` would be too broad.) The form in question looked roughly like this:
```
<form id="my-form-id">
  <div class="row">
    <div class="form-group">
      <label for="name">Thing name</label>
      <input class="form-control" name="name"></input>
    </div>
  </div>
  <div class="row">
    <div class="form-group">
      <label for="info">Thing description</label>
      <textarea class="form-control" name="info"></textarea>
    </div>
  </div>
  <button type="submit" class="btn disabled">Save</button>
</form>
```
...that is, with multiple levels between the outer `<form>` tags and the inputs that I care about.

Within Syphon, in `getForm`, `_.isUndefined(viewOrForm.$el)` returned `true`, since the form itself doesn't have an `$el`. That meant `getForm` returned `$(viewOrForm).children(':input')`. But since `$.children` <a href="https://api.jquery.com/children/">only looks one level deep</a>, Syphon didn't find any matching elements and didn't extract any data.

So: since `Backbone.View.$`, which you use to handle views, <a href="http://backbonejs.org/#View-dollar">uses `$.find`</a>, and since `$.find` would find everything `$.children` does, why not go with `$.find` here, like this? https://github.com/marionettejs/backbone.syphon/compare/master...david-davidson:use-jquery-find

Thanks for your time, and for your tremendously useful product!

**Comment by rhubarbselleven** [comment]
Hi @david-davidson which version are you using?

**Comment by studio-marweb** [comment]
Hi @rhubarbselleven, I agreed with @david-davidson. It would be great if getForm will use jquery find method instead children.

**Comment by david-davidson** [comment]
@rhubarbselleven, sorry for the delay! I'm on `backbone.marionette: 2.4.1` and `backbone.syphon: 0.6.0`.

**Comment by rhubarbselleven** [comment]
Coolies, anyone interested in a quick PR?

**Comment by david-davidson** [comment]
Will do!

**Comment by rhubarbselleven** [comment]
Thanks for your perseverance on this one @david-davidson
