### ISSUE TITLE
Compatibility issue with Cocktail Library

### ISSUE THREAD

**Issue by maximerassi** [marionettejs/backbone.syphon#105]
A function in Backbone.Syphon gets corrupted if (``Backbone.Syphon`` - https://github.com/marionettejs/backbone.syphon) library is loaded before the (``Cocktail`` - https://github.com/onsi/cocktail) library. I did not yet get to the bottom of it as to why but here is the problem.

**Problem**
If the ``Cocktail`` library is loaded after loading the ``Backbone.Syphon`` library then the ``Backbone.Syphon.keyJoiner``, which is normally a function is now a string with value ``undefined[undefined]``. It seems somehow the function was auto executed and the value was re-assigned on itself.

**Expected**
```
Backbone.Syphon.keyJoiner = function (parentKey, childKey){
  return parentKey + "[" + childKey + "]";
}
```

**Actual**
```
Backbone.Syphon.keyJoiner = 'undefined[undefined]'
```

**Reproduce with the Breaking Situation**
```
<!DOCTYPE html>
<html>
<head>
<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="http://jashkenas.github.io/underscore/underscore-min.js"></script>
<script src="http://jashkenas.github.io/backbone/backbone-min.js"></script>
<script src="https://raw.githubusercontent.com/marionettejs/backbone.syphon/master/lib/backbone.syphon.js"></script>
<script src="https://raw.githubusercontent.com/onsi/cocktail/master/Cocktail.js"></script>
  <meta charset="utf-8">
  <title></title>
</head>
<body> 
  <script type="text/javascript">
    console.info('Backbone ' + Backbone);
    console.info('Syphon ' + Backbone.Syphon.keyJoiner); // undefined
  </script>
</body>
</html>
```

**Reproduce with the non Breaking Situation**
```
<!DOCTYPE html>
<html>
<head>
<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="http://jashkenas.github.io/underscore/underscore-min.js"></script>
<script src="http://jashkenas.github.io/backbone/backbone-min.js"></script>
<script src="https://raw.githubusercontent.com/onsi/cocktail/master/Cocktail.js"></script>
<script src="https://raw.githubusercontent.com/marionettejs/backbone.syphon/master/lib/backbone.syphon.js"></script>
  <meta charset="utf-8">
  <title></title>
</head>
<body> 
  <script type="text/javascript">
    console.info('Backbone ' + Backbone);
    console.info('Syphon ' + Backbone.Syphon.keyJoiner); // function ...
  </script>
</body>
</html>
```

**Linked Issue**
https://github.com/onsi/cocktail/issues/51

**Comment by rhubarbselleven** [comment]
Hi @maximerassi I don't feel this is a Syphon issue. I'd imagine you're experiencing this because of something here: https://github.com/onsi/cocktail/blob/master/Cocktail.js#L29-L47. Most likely where it assigns a function with an `obj[key]`. Just a guess.
