### ISSUE TITLE
Using with a Twitter Bootstrap styled form.

### ISSUE THREAD

**Issue by andrewdaymaster** [marionettejs/backbone.syphon#111]
Maybe I've been misusing this, but In the lastest release version 0.5. I can style a form with bootstrap e.g. have nested divs with the inputs and when syphon is called it will pull out the nested inputs and serialize the data. With 0.6 it seems the change to the getForm function has removed this ability.

``` HTML
<form class="form-horizontal">           
        <div class="form-group">
            <label for="example" class="col-lg-2 control-label">Subject</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="example" name="example">
            </div>
        </div>
</form>
```

**Comment by jwhitfieldseed** [comment]
This should be fixed by https://github.com/marionettejs/backbone.syphon/pull/110.

**Comment by andrewdaymaster** [comment]
@jwhitfieldseed Thanks for the response
