### ISSUE TITLE
Uncaught TypeError: config.keyJoiner is not a function

### ISSUE THREAD

**Issue by ErikEvenson** [marionettejs/backbone.syphon#115]
I am getting the following errror:

```
Uncaught TypeError: config.keyJoiner is not a function
```
on this line of syphon code:

[https://github.com/marionettejs/backbone.syphon/blob/v0.6.2/lib/backbone.syphon.js#L296](https://github.com/marionettejs/backbone.syphon/blob/v0.6.2/lib/backbone.syphon.js#L296)

Here is my current front-end stack:

```
  "dependencies": {
    "backbone": "1.1.2",
    "backbone.paginator": "2.0.2",
    "backbone.picky": "0.2.0",
    "backbone.syphon": "0.6.2",
    "backgrid": "0.3.5",
    "backgrid-filter": "0.3.5",
    "backgrid-moment-cell": "0.3.5",
    "backgrid-paginator": "1730e0231c51d4606945a3d3492213ec37b9dcdc",
    "backgrid-select-all": "0.3.5",
    "bootstrap": "3.2.0",
    "bootstrap3-datetimepicker": "4.7.14",
    "highcharts-release": "4.0.3",
    "jquery": "1.10.2",
    "json2": "*",
    "marionette": "1.8.5",
    "moment": "2.5.1",
    "numeral": "1.5.3",
    "spin.js": "2.0.1",
    "underscore": "1.6.0",
    "moment-timezone": "0.2.2",
    "papaparse": "3.1.2",
    "async": "0.9.0"
  },
  "resolutions": {
    "underscore": "1.6.0",
    "moment": ">= 2.6.0"
  }
```

What might be wrong?

**Comment by samccone** [comment]
@ErikEvenson what is config?

how are you using syphon?

**Comment by ErikEvenson** [comment]
I'm not entirely sure what config is as it is part of syphon.  I use syphon to pull results out of forms, but this error occurs on a page without any forms -- so it must be an initialization error.

**Comment by samccone** [comment]
Can you post the js stack trace?

**Comment by ErikEvenson** [comment]
Sure:

![screen shot 2015-08-06 at 10 18 47 pm](https://cloud.githubusercontent.com/assets/166395/9128088/4693588a-3c89-11e5-96b7-de1821a98ba0.png)

**Comment by ErikEvenson** [comment]
Also, sorry, there is a form on this page.

**Comment by ErikEvenson** [comment]
Turns out I was using an old version of syphon by accident on that instance.  Using the current release fixed the problem.  Sorry for the false alarm.  Thanks for the attention and the great tool.  Closing.

**Comment by samccone** [comment]
:+1: :clap:
