### ISSUE TITLE
Wrong latest release on github (v0.6.1)

### ISSUE THREAD

**Issue by berniegp** [marionettejs/backbone.syphon#118]
For some reason, github considers v0.6.1 as the latest release instead of v0.6.3. However, npm correctly uses v0.6.3.

**Comment by berniegp** [comment]
![2015-11-10_23-38-48](https://cloud.githubusercontent.com/assets/881558/11084061/ba157132-8804-11e5-8698-6444e18bba29.png)

**Comment by samccone** [comment]
one moment, just need to release a tag on gh

**Comment by samccone** [comment]
thx for the spot @berniegp
