### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by pouu69** [marionettejs/backbone.syphon#122]
Cannot read property 'toString' of undefined

what is it?

**Comment by samccone** [comment]
... context?

**Comment by pouu69** [comment]
Backbone.syphon.desirialize(this, {key:val});

**Comment by samccone** [comment]
@pouu69 can you provide a jsfiddle to reproduce this error, currently there is not enough information to make this something that anyone can help you debug efficiently.

**Comment by rhubarbselleven** [comment]
@pouu69 is this still an issue for you? Can you provide the jsfiddle requested?

**Comment by scott-w** [comment]
I'm closing this in favour of #124
