### ISSUE TITLE
Update cdnjs to point to this repo

### ISSUE THREAD

**Issue by inspiredbytes** [marionettejs/backbone.syphon#123]
cdnjs points to points to https://github.com/derickbailey/backbone.syphon/
It should probably be updated to https://github.com/marionettejs/backbone.syphon

See https://cdnjs.com/libraries/backbone.syphon

If I understand cdnjs's readme correctly, it looks like they are requesting project maintainers to submit PRs rather than manual submissions.
https://github.com/cdnjs/cdnjs

**Comment by rhubarbselleven** [comment]
Thanks for the heads up @inspiredbytes 

xref: https://github.com/cdnjs/cdnjs/pull/6956
