### ISSUE TITLE
Deserialize an undefined property matching a radio input

### ISSUE THREAD

**Issue by daolf** [marionettejs/backbone.syphon#124]
Hi, there is strong chance this issue is related to the [#122](https://github.com/marionettejs/backbone.syphon/issues/122), but because there is no way to be sure I created a new one, feel free to move it though.

It appears that if you deserialized an object with an undefined property, and if that property match a radio input you would get that error.

It all happens here l:420:

``` javascript
  // Radio button writer, set whether or not the radio button is
  // checked.  The button should only be checked if it's value
  // equals the given value.
  InputWriters.register('radio', function($el, value) {
    $el.prop('checked', $el.val() === value.toString());
  });
```

Because value would be undefined, value.toString would raised a "Cannot read property 'toString' of undefined".

Can submit the one line pr.

**Comment by daolf** [comment]
Proposal fix :

```javascipt
  // Radio button writer, set whether or not the radio button is
  // checked.  The button should only be checked if it's value
  // equals the given value.
  InputWriters.register('radio', function($el, value) {
    if (value !==undefined) {
    }
  });

```

**Comment by joshhoegen** [comment]
Having the same issue with v0.6.3 and have confirmed @daolf's proposal works.

**Comment by ishaikovsky** [comment]
Same issue.. Looking for workaround meanwhile.. But that should be fixed..

**Comment by scott-w** [comment]
Hi @daolf, thanks for uncovering this. I'm looking at resolving this bug. If you could provide the HTML that you used to generate this error, that would be a great help!

**Comment by scott-w** [comment]
Never mind, I have it @daolf - it's on the deserialize side.
