### ISSUE TITLE
Add Backbone 1.3.* support

### ISSUE THREAD

**Issue by alex-shamshurin** [marionettejs/backbone.syphon#128]
Because BB 1.2  breaks some webpack dependencies and this is only one package in my package.json which use BB 1.2. All other packages use 1.3.

**Comment by samccone** [comment]
sure, we can update this

@salex772 any interest in opening a PR?

**Comment by salex772** [comment]
As I see right now there is a PR https://github.com/marionettejs/backbone.syphon/pull/65

**Comment by MeoMix** [comment]
The scope of that PR dwarfs the scope of a PR bumping BB version range.

I don't see any reason why Backbone.syphon can't just trivially bump to 1.3.3. Most of the changes to BB are just bug fixes according to the changelog.

**Comment by salex772** [comment]
Of course, it will be good to update because under webpack it leads to multiple BB instances and breaks marionette app (unrecognized radio error).

**Comment by paulovieira** [comment]
Please publish a new version to npm as well (with support for Backbone 1.3.x).

**Comment by scott-w** [comment]
Backbone 1.3.3 is now supported as of Syphon 0.7.0
