### ISSUE TITLE
lib folder is not updated in major?

### ISSUE THREAD

**Issue by ishaikovsky** [marionettejs/backbone.syphon#130]
I really have two questions here:

1) looking to **major** branch I see that src/backbone.syphon.js file was updated a year ago while the lib/backbone.syphon.js - 2. And so the second one doesn't have changes that was made in the first (e.g. I'm interested in disabled field ignore fix).

2) correct me if I'm wrong but the npm build is still doesn't have major changes? E.g. same issue with ignore disabled seems to be merged to major year ago but never released?

Thanks!
Ilya

**Comment by scott-w** [comment]
I'm closing this as we've now released v0.7.0
