### ISSUE TITLE
Backbone Syphone serialization issue on selection of combobox items using tab

### ISSUE THREAD

**Issue by pushpendragzb** [marionettejs/backbone.syphon#29]
Hi All,

              I am using backbone.syphone to serialize my backbone forms.
              Its working fine in the normal case.
              I am using jqwidgets for Ui.
              So when i serialize the form containing jqxcombobox(item selected by tab not by mouse) its gives name in serialized data not value of selected item of combobox.

For Instance  we have following content inn the form:
HTML: 
<form id="abs">
<div id="contact_id">
</form>

Javascript:

            $("#contact_id").jqxComboBox({
                source: contacts,
                selectedIndex: -1,
                promptText: "Select Customer",
                width: '75.5%',
                height: '20',
                theme: 'ui-start'
            });

what is contacts:

                    var contactItem = {
                        html: "",
                        label:A,
                        value:1
                    };
                    contacts.push(contactItem);
                    var contactItem1 = {
                        html: "",
                        label:A,
                        value:1
                    };
                    contacts.push(contactItem1);

Now Serialization:

Case One : Select list item by mouse selection 
                 It works well gives the value of selected index.
Case Two: Select list item by keyboard tab key.
                It gives label string on serialization.

I need value of selected index in both cases.

Please suggest me a solution.

Thanks in advance.

Regards,
Pushpendra

**Comment by rhubarbselleven** [comment]
Hi @pushpendragzb, any update on this one?

**Comment by rhubarbselleven** [comment]
Hi @pushpendragzb, closing this one for now. Feel free to re-open if you're still having this issue
