### ISSUE TITLE
undefined keyExtractors

### ISSUE THREAD

**Issue by seferov** [marionettejs/backbone.syphon#36]
When I try to serialize a view, it gives the error:
```
Uncaught TypeError: Cannot call method 'get' of undefined 
```
on
```
var extractor = config.keyExtractors.get(type);
```

**Comment by rhubarbselleven** [comment]
Hi @seferov any update on this?

**Comment by rhubarbselleven** [comment]
Hi @seferov I'll close this one for now. Feel free to re-open if you're still experiencing troubles
