### ISSUE TITLE
Radio Buttons groups non selected default

### ISSUE THREAD

**Issue by maraujop** [marionettejs/backbone.syphon#6]
Hi Derick,

First, I want to thank you very much your work on Backbone open source and your tons of tutorials online, they are extremely helpful for people getting into this world.

I've started using this plugin in the project I'm working right now and it's been great. But today I've found that when I serialize a form with a radio buttons group, without any radio selected, data serialized does not contain the key for that radio button group. I'm not sure if this is the intended behavior. This forces me to check for `undefined`.

Wouldn't it be better to have the name as a key of `data` and an empty string as its default?

Thanks, cheers
Miguel

**Comment by naoisegolden** [comment]
Although this is by design, I don't really see the point on forcing to define a default value in the model instead of falling back to leave all radio inputs checked, for example. This is a hard "bug" to debug and probably happens in most creation forms with radio buttons.
