### ISSUE TITLE
bower update

### ISSUE THREAD

**Issue by t2k** [marionettejs/backbone.syphon#69]
Bower is still configured with Deriks version at derikbailey/backbone.syphon

Is this meant to be the maintained version?

**Comment by rhubarbselleven** [comment]
@samccone to ping @derickbailey re updating the published bower url to drive this one home

**Comment by samccone** [comment]
@derickbailey said that he is not the owner any more... looks like we will need to ping them on the issue

**Comment by derickbailey** [comment]
I'm not sure if it's me or not... i couldn't find the package in bower. how do i check that? i never used bower, and someone else set this up originally.

**Comment by rhubarbselleven** [comment]
The registration would of occurred when Syphon was a part of your repositories. After the creation of the organisation, well I guess bower doesn't support that transition.

Looks like dropping a comment on this one https://github.com/bower/bower/issues/120 is the way to go

**Comment by derickbailey** [comment]
ok, dropped a comment there. hopefully it will happen.

**Comment by rhubarbselleven** [comment]
:+1: Thanks Derick

**Comment by samccone** [comment]
:+1: :+1: thanks @derickbailey

**Comment by nonrational** [comment]
@derickbailey looks like it happened. :boom: 

but, need to re-register with correct repo url. right now, bower can't find backbone.syphon at all.
```
bower backbone.syphon#0.4.1                   ENOTFOUND Package backbone.syphon not found
```

**Comment by samccone** [comment]
BOOOOOM on it @nonrational

**Comment by samccone** [comment]
:boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: 
PUBLISHED
:boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom:

**Comment by nonrational** [comment]
:loud_sound: :rotating_light: 

awesome! nice work @samccone

**Comment by samccone** [comment]
thanks for letting me know @nonrational your the man :goat:

**Comment by rhubarbselleven** [comment]
omg happypanda

Thanks guys :dancer: :balloon:

**Comment by samccone** [comment]
:panda_face:
