### ISSUE TITLE
Adding File Input to Model

### ISSUE THREAD

**Issue by ramsunvtech** [marionettejs/backbone.syphon#74]
I have multipart/form-data Form with one File field. Below code is not getting the File data.

`var data = Backbone.Syphon.serialize(this);`

Is there any solution available n Syphone for File data ?

**Comment by rhubarbselleven** [comment]
Hi @ramsunvtech 

The result of `.val()` on 

```
<input type="file" />
```

Would be the filename, not the file contents. If you're looking to serialise the contents of a file into a JavaScript object then you'll need a different library.

Does this help?

**Comment by ramsunvtech** [comment]
I'm looking for file content not the filename !

**Comment by thejameskyle** [comment]
There are a number of things that would need to be solved here, but seem very out of scope for this project. You're gonna want a separate library that can solve this better :-1:

**Comment by samccone** [comment]
yep this seems like it does not belong in core. If you are looking to serialize the file contents you would want to use something like the file reader api to dump the contents as a binary blob, and do whatever you want. I don't think we want to support this by default.
