### ISSUE TITLE
Possible issue with existence check

### ISSUE THREAD

**Issue by BorisKozo** [marionettejs/backbone.syphon#77]
https://github.com/marionettejs/backbone.syphon/blob/master/src/backbone.syphon.typeregistry.js#L36
I think this line should be something like
```js
if (this.registeredTypes.hasOwnProperty(type))
```

So that falsy values can be inserted into the registry

**Comment by rhubarbselleven** [comment]
Hi @BorisKozo, nice catch. Mind creating a PR?

**Comment by BorisKozo** [comment]
Sure, I will try to get to it tomorrow (technically its 11:40 PM here :) )

**Comment by rhubarbselleven** [comment]
:+1:  great stuff, thanks

**Comment by rhubarbselleven** [comment]
Fixed with #86. Thanks @BorisKozo
