### ISSUE TITLE
Using :input instead of form

### ISSUE THREAD

**Issue by rhubarbselleven** [marionettejs/backbone.syphon#92]
Currently, Syphon expects there to be a form element and from there will begin the serialisation process.

But what if there are 2 form tags? What if there isn't a form tag?

This issue is to land #18 (excluding handling default fields) by using [:input](http://api.jquery.com/input-selector/) as a means to collect form fields in a fragment

**Comment by samccone** [comment]
yes plz :+1:

**Comment by darko1002001** [comment]
+1

I have an example where i am using Syphon to deserialize into fields inside a table. i have a itemView for each row which does the deserialization based on the model. I cannot rely on a form tag to for the row. this proposed solution will be perfect for these use cases.

**Comment by rhubarbselleven** [comment]
Will be out in the next release :dancers:
